In [3]:
import pandas as pd
import numpy as np
import joblib
from sklearn.dummy import DummyRegressor
from sklearn.ensemble import RandomForestRegressor, GradientBoostingRegressor
from sklearn.model_selection import GridSearchCV
from sklearn.linear_model import LinearRegression, Ridge, Lasso, ElasticNet
from sklearn.svm import SVR
from sklearn.neighbors import KNeighborsRegressor
from xgboost import XGBRegressor
from sklearn.tree import DecisionTreeRegressor
from sklearn.metrics import mean_absolute_error, r2_score, mean_squared_error

In [5]:
# function to load the model
model_file = '/Users/blairjdaniel/lighthouse/lighthouse/NHL/NHL_points_projection/models/skater_gradient_boosting_model.pkl'
def loadModel(model_file):
    '''
        This function loads a model from a pickle file.

        inputs:
            model_file:     string indicating the file location
        outputs:
            model:          the trained model
    '''
    model = joblib.load(model_file)
    return model

In [6]:
train_df = pd.read_csv('/Users/blairjdaniel/lighthouse/lighthouse/NHL/NHL_points_projection/processed/X_train_pca.csv')
test_df = pd.read_csv('/Users/blairjdaniel/lighthouse/lighthouse/NHL/NHL_points_projection/processed/X_test_pca.csv')

             0         1         2
0    -1.820017  1.696154  0.021523
1    -1.663445  0.724064 -0.015047
2    -1.669147  1.700097  0.003866
3     2.197887 -1.106910 -0.729234
4    -0.774229  1.693636  0.043292
...        ...       ...       ...
2285 -2.033129 -0.178456 -0.428723
2286 -1.522469 -0.272731  0.085941
2287  2.749752 -0.526189  1.602009
2288 -1.065351 -0.330787  0.425727
2289 -1.695973 -0.222037 -0.178728

[2290 rows x 3 columns]